on:
  push:
  pull_request:

name: check

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      - name: Install Armadillo
        run: sudo apt-get install libarmadillo-dev

      #- name: Install libmlpack-dev, DON'T! See https://github.com/mlpack/mlpack/issues/3274
      #  run: sudo apt-get install libmlpack-dev

      - name: Install libmlpack-dev from source, see https://github.com/mlpack/mlpack/issues/3274
        run: |
          cd ..
          git clone https://github.com/mlpack/mlpack --depth 1
          cd -
          # No need to build it
          # cd mlpack
          # mkdir mlpackbuild && cd build/
          # cmake ../
          # sudo make install          
          # cd ../../
          # cd mlpack_example_2

      - name: Install libcereal-dev
        run: sudo apt install libcereal-dev

      #- name: Install libensmallen-dev
      #  run: sudo apt-get install libensmallen-dev

      #- name: Install Codecov
      #  run: sudo pip install codecov

      - name: qmake
        run: qmake mlpack_example_2.pro

      - name: make
        run: make debug --silent

      - name: run
        run: ./mlpack_example_2

      #- name: Measure codecov
      #  run: |
      #    ./get_code_cov.sh
      #    codecov
      #    bash <(curl -s https://codecov.io/bash)
